version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    image: sadekmissaoui/quote-scraper:latest
    ports:
      - 5000:5000
    restart: unless-stopped
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: root
      MONGODB_DATABASE: quotes_db
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    networks:
      - database-net
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: quotes_db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - quotes-mongodb-data:/data/db
    networks:
      - database-net

volumes:
  quotes-mongodb-data:

networks:
  database-net: